### ISSUE TITLE
Debugging Engine fails to install the debugger in the JSContext

### ISSUE THREAD

**Issue by wehrstedt** [otris/vscode-janus-debug#102]
[vscode-janus-debug-launch.txt](https://github.com/otris/vscode-janus-debug/files/1228522/vscode-janus-debug-launch.txt)
Extension version: 0.9.0
Documents: 2040 (installed today on ubuntu)
Problem:
I tried to debug a simple script, but the debugger wont work. This is my script:
```
util.out("hey");
util.out("ho");
util.out("hi");
```

I placed my breakpoint on line 2. This is the server output:
```
Client 29: c_term: JavaScript error: Couldn't start debugger.
Client 29: c_term: hey.
Client 29: c_term: ho.
Client 29: c_term: hi.
2017-08-16 16:32:07.206: Client 29: c_term: Client 29 disconnected.
```

The debugger was not started and the script executed normal. Also tried to insert "debugger;" between line 1 and 2 but the problem is still the same.

The debugger flag in the ini file is set to "yes".
Is there a problem with the documents server?

**Comment by bkircher** [comment]
> Documents: 2040 (installed today on ubuntu)

Can you give me the exact package version? Something along the line

```sh
$ dpkg -s documents5-mysql | grep -i version
```

should do the trick.

**Comment by wehrstedt** [comment]
Version: 1:5.0c-2040-1360ubuntu0.16.04

**Comment by wehrstedt** [comment]
Ok, this seems to be a problem with the documents server. I updated my documents installation today (Version: 1:5.0c-2040-1363ubuntu0.16.04). When I try to debug a script via launch request the error is still the same.
If I insert a "debugger;" statement inside the script, the debugger stops correct. When I try to attach the vscode debugger, I get "connection refused". Here is the log:
```
INFO |00000.313|JanusDebugSession: readConfig: {"name":"Attach to Server","request":"attach","type":"janus","host":"localhost","debuggerPort":8089,"log":{"fileName":"e:\\otrTerm/vscode-janus-debug-attach.log","logLevel":{"default":"Debug"}},"__sessionId":"3a4e8f30-3bcc-42aa-95ae-f2cdad21668e"}
INFO |00000.314|JanusDebugSession: attachRequest
DEBUG|00000.322|DebugAdapterIPC: disconnected from VS Code extension
ERROR|00001.325|JanusDebugSession: failed to connect to localhost:8089: ECONNREFUSED
ERROR|00001.326|JanusDebugSession: remote closed the connection due to error
INFO |00001.327|JanusDebugSession: disconnectRequest; debug adapter running in attach config
```

But the credentials in my launch.json are correct.

**Comment by wehrstedt** [comment]
hmm..the debugger tries to connect to "localhost", but in my launch.json is an other ip...

**Comment by wehrstedt** [comment]
Updated the problem description because I didn't changed my creadentials for attach requests. Now I got a timeout-error

**Comment by bkircher** [comment]
Thanks for reporting. The VS Code client gets a ETIMEDOUT because the server fails to install the debugger in the JSContext that is going to be executed. The script is executed but without a debugger attached. Thus the TCP port for the debugger is not opened and VS Code client timeouts on connect.

Errors like this occur when multiple scripts are running simultaneously or one script is being halted while another is started. One way to circumvent this problem is to restart the server.

@PhilippRo is working on a patch to JANUS to install the debugger engine a bit differently that should fix most of those issues. These changes are mostly done but require more testing on our side. We think we integrate these changes some time around next week and eventually they will land in DOCUMENTS 5.0c or 5.0d after that.

**Comment by bkircher** [comment]
These type of issues are solved in recent D5.0d builds. Please re-open or file a new issue if this problem persists.
