### ISSUE TITLE
Generate d.ts file for filetypes

### ISSUE THREAD

**Issue by tineheller** [otris/vscode-janus-debug#119]
This `d.ts` files will contain the fieldnames and fieldtypes. Then it will be possible to get IntelliSense for fields by inserting the filetype as `@type` in a JSDoc comment.

**Example**

![intellisenseft](https://user-images.githubusercontent.com/25297240/30795478-043b650c-a1ce-11e7-8f86-32b9f79d7c1b.png)

The files will be generated when calling the command **Install Intellisense Files**. Maybe an additional command will be provided for generating only one FileType.

**Comment by FabianTe** [comment]
First: **Really love the idea!**
Second: The following is how I'd generate the typings file. Only a suggestion / hint, not a proposal :wink: 

Currently I create my custom typings files. They contain my declaration for my filetypes and look like this:

```typescript
// The interface extends the DocFile class so that it holds all of its functions
declare interface InvoiceDocFile extends DocFile {
	Gross:		number;
	Net:		number;
}

// InvoiceDocFile is declared as an interface and not a class to prevent this from working ...
var file = new InvoiceDocFile();

// ... while stuff like this will work:
context.file.sync();
```

I admit that I use Typescript exclusively for developing and only this propably wouldn't work but you can add the following to your typings file and combine it with your approach to make it work:

**Typings**
```typescript
declare type TInvoiceDocFile = InvoiceDocFile;
```

**JavaScript**
```javascript
/**
 * @type {TInvoiceDocFile}
 */
var file = context.file;
```

Maybe this is exactly how you'd do it, otherwise I'm happy to share how I handle that topic currently.

**Comment by tineheller** [comment]
Ok, thank you for the hints! I think I will declare the filetypes as interfaces.

Additional I will add a mapping to get IntelliSenser for this:
```
var docFile2 = context.createFile('Filetype4');
```

**Comment by tineheller** [comment]
I just published a first version (0.0.16). For this first version I inserted the additional command **Get fileTypes.d.ts**. This file only contains the field names but all field names still have `any` type. Because getting the types from server is a bit more difficult this will take a bit longer.

**Comment by FabianTe** [comment]
The field types should match the the appropriate JS type.

```typescript
FirstName: string;
Age: number;
Birthday: Date;
```

**Comment by tineheller** [comment]
Yes I know and I'll do that. But as I mentioned in my last comment, getting the types from the server is a bit more difficult. So I'm not sure when I can insert them.

**Comment by tineheller** [comment]
With the next version of DOCUMENTS (\#8044 or 5.0c HF1) and the next version of the extension (0.0.23) suitable types will be inserted for the fields in `fileTypes.d.ts`.
