### ISSUE TITLE
Extensions can now add intellisense to TS and JS files

### ISSUE THREAD

**Issue by derrohrbach** [otris/vscode-janus-debug#141]
Hey, since the January Update VSCode extensions can provide additional IntelliSense, Linting, etc. for TypeScript and JavaScript. This might be interesting as an alternative for the typings, since you do not have to install anything and can provide additional dynamic features like filetype definitions, snippets and other autocomplete functions

For reference: [https://code.visualstudio.com/updates/v1_20#_extension-contributed-typescript-plugins](https://code.visualstudio.com/updates/v1_20#_extension-contributed-typescript-plugins)

**Comment by tineheller** [comment]
That looks interesting, thanks for the hint!

**Comment by FabianTe** [comment]
This might be a better implementation, yes. But I'd not want DOCUMENTS / etc IntelliSense in non DOCUMENTS workspaces. I think it should be able to toggle this on / off.

**Comment by derrohrbach** [comment]
You could also only turn it on if there is a launch configuration

**Comment by tineheller** [comment]
Well I only had a small look... but I think this is only for language server extensions. And I think with a language server it's not possible to add the IntelliSense via `d.ts` files. But I cannot add IntelliSense in another way, because the PortalScript API is very big and it's growing, so it has to be generated. It's easy to generate the `d.ts`. But for all I know about language servers, it's not easy to generate IntelliSense that can be provided by a languge server. Additional we need the `d.ts` files for users who want to write their scripts in TypeScript. And we are working on improving TypeScript support.

**Comment by FabianTe** [comment]
To be honest I don't mind the typings files that much since I use them anyway to document custom objects / classes or libraries I imported into PortalScripting.

**Comment by derrohrbach** [comment]
It was just meant an idea/heads up that such a feature exists now and might come in handy

**Comment by tineheller** [comment]
Yes, thank you! I'm always happy about any kind of hints.
But for now I can't use this feature, so I'll close the issue.
