### ISSUE TITLE
Extension doesn't use launch.json information

### ISSUE THREAD

**Issue by m-Schlitzer** [otris/vscode-janus-debug#145]
Steps to reproduce:
- create launch.json
- try to upload script to server via `DOCUMENTS: Upload Script`

Expected Behaviour:
The extension should get the necessary information from the launch.json and not ask again.

My launch.json:
![screenshot from 2018-03-01 15-00-52](https://user-images.githubusercontent.com/20104782/36848491-aa30054e-1d61-11e8-9880-6f6ae65afd20.png)

The extensions behaviour:
![screenshot from 2018-03-01 14-59-40](https://user-images.githubusercontent.com/20104782/36848522-c431d65c-1d61-11e8-8413-aa3f25c5f0d9.png)

**Comment by tineheller** [comment]
Well, the extension just looks into the `launch.json` and if only one required information is missing (in your case it's the principal) the user is asked to insert all information again.
But you're right, actually that is a bit stupid. First of all because the extension won't save the newly inserted information when the `launch.json` already exists.
So I will change that and only ask for the information if the `launch.json` does not exist. If it exists, the information will be taken from there and you will get an error message when something is missing.

**Comment by tineheller** [comment]
I think this should work as expected now. Additional, if the server is an empty string, the extension will now try to connect to localhost. This is provided by the connection module. But in my opinion this is a feature, so for now I will keep it that way.

Done with 61e0882b6e2719e70dbbc4a205388050270b528d and 794bbb1c4b9320e1555589da8c87a421a689b79a
