### ISSUE TITLE
No global return

### ISSUE THREAD

**Issue by fiurthorn** [otris/vscode-janus-debug#155]
Omit global return statement use `contex.returnCode` or an `exit()` function instead.

**Comment by tineheller** [comment]
I'm not sure what you mean, could you give an example?

**Comment by FabianTe** [comment]
This is how I understand it:

Example: UDA scripts that want to display some kind of user error have to return -1.

```js
context.errorMessage = "This is the user error";
return -1;
```

When working with a JS linter or worse typescript every `return -1` in each script is perceived as one error.

What I think @fiurthorn is suggesting, is an alternative approach to change the PortalScript behaviour for return values. Instead of using `return -1`, having an option like `context.returnCode` would result in code that isn't perceived as faulty by linters and so on:

```js
context.errorMessage = "This is the user error";
context.returnCode = -1;
```

To ensure backwards compatibillity a `return ...` maybe could still be possible.
I don't know if this is possible in the DOCUMENTS / PortalScripting architecture though.
