### ISSUE TITLE
Restart debugging fails

### ISSUE THREAD

**Issue by wehrstedt** [otris/vscode-janus-debug#182]
If you run `Upload and debug script` and the press the restart button, it fails with the message "No script to launch"

**Comment by tineheller** [comment]
Well, actually at the moment this is expected. Because in **Upload and Debug Script** the script is not started with the debugger but with the extension. So the debugger can not restart a script because it has never started a script.
The resart will maybe only work when the debugger is used in the usual **Launch** mode. Meaning, typing the scriptname in `launch.json` and launch it via the **Launch** button. But this mode is not supported yet or at least not tested.

**Comment by tineheller** [comment]
Actually we should move the call of `uploadDebugScript()` to `launchRequest()`. Then we only have to think about how to get the values of the launch configuration entries `script` and `portal`.
* **Restart:** the entries can be kept in the `__restart` argument (this argument is made for this reason)
* **Launch:** the entries must be read from `launch.json`

**Comment by tineheller** [comment]
Workaround:
Pressing the stop button and calling **Upload and Debug Script** again should work.

**Comment by tineheller** [comment]
The project was moved to GitLab
https://gitlab.otris.de/tools/vscode-janus-debug/issues/182
