### ISSUE TITLE
Select dialog if local script was found multiple times

### ISSUE THREAD

**Issue by wehrstedt** [otris/vscode-janus-debug#192]

**Comment by tineheller** [comment]
When the user's workspace contains multiple scripts with same name and the user want to debug a script with that name, they should get a dialog to select the script with the correct path.

To implement this, both the path and the source code must be kept in the `LocalSource` object. Actually, this is a good idea anyway. Because at the moment the source code is loaded from disk every time it is required (meaning on every stop event like every single step!).
