### ISSUE TITLE
Search #import'ed scripts to improve IntelliSense

### ISSUE THREAD

**Issue by idolum** [otris/vscode-janus-debug#32]
As requested in the other  [issue](https://github.com/otris/vscode-documents-scripting/issues/8) the issue for supporting automatic imports of Documents script is submitted here again. 

**The issue is:**
By using the `#import` clause, a Documents script can import the the code of other scripts. Unfortunately, the functions et al. defined in these imported scripts are not available in the code completion list. Only, by open the corresponding files manually.

There are extensions available, able to search the workspace files and provide the found functions to the code completion without open the files:

- [TypeScriptImporter](https://marketplace.visualstudio.com/items?itemName=pmneo.tsimporter)
- [Auto Import](https://marketplace.visualstudio.com/items?itemName=steoates.autoimport)

Something similar that either searches all workspace files or scans the `#import` clauses of a script and resolve them and load their content to the code completion would be nice. But the mechanism should consider that not some scripts may located in the `bower_components` folder, some solutions/modules make use of the functionality provided by other modules linked via bower.

**Comment by bkircher** [comment]
Thanks for re-submitting.

Do I understand you correctly this is only about making VS Code IntelliSense work with #import?

**Comment by idolum** [comment]
From my point of view, yes! But of course there is a dependency to issue #27.

**Comment by bkircher** [comment]
As a matter of fact, @roest01 asked me about this two days ago, complaining why this wouldn't work in VS Code because it does work out of the box with WebStorm (independently of `#import`).

> But of course there is a dependency to issue #27

Actually, I don't think so. This here can be implemented completely independent of how `#import` actually works on the server. Also, results do not have to be _that_ precise, IMO. If you miss a file you just won't get auto completion on functions or properties in that single file. In #27 OTOH your debugging experience will be quite shitty if you are only off by a single line.

Question: Which is more important to you or which should we do first (just suppose we have to pick one)? #32 or #27?

**Comment by idolum** [comment]
#27 is more important than #32. We can use jsconfig.json.

**Comment by tineheller** [comment]
I will close this issue, because the way of getting IntelliSense for all files in your project is creating a jsconfig.json (see [JavaScript Project](https://code.visualstudio.com/docs/languages/javascript#_javascript-project-jsconfigjson))
