### ISSUE TITLE
Upload JavaScript file from TypeScript file

### ISSUE THREAD

**Issue by tineheller** [otris/vscode-janus-debug#55]
The extension should provide a command to transpile a TypeScript file to a JavaScript file and upload the JavaScript file.

For instance, if you have the following TypeScript file open in your VS Code

```
//#import "test_VSCode_folder1"

var myfile = context.file;
if(myfile) {
    var myname: string = myfile.getFieldName(0);
}

class myClass {
    public myVar: number;
}

util.out(">>>>>>>>>>>>>>>>: " + scriptName);
```

the TypeScript compiler will produce the following JavaScript file

```
//#import "test_VSCode_folder1"
var myfile = context.file;
if (myfile) {
    var myname = myfile.getFieldName(0);
}
var myClass = (function () {
    function myClass() {
    }
    return myClass;
})();
util.out(">>>>>>>>>>>>>>>>: " + scriptName);
```

and the extension will upload this file automatically after the compilation.

The problem is, if the JavaScript file is changed on the server, it will not match the TypeScript file anymore. But for now, this problem must be handeled by the user.

**Comment by FabianTe** [comment]
> The problem is, if the JavaScript file is changed on the server, it will not match the TypeScript file anymore. But for now, this problem must be handeled by the user.

If the user had a full working build pipeline that shouldn't be a problem. Personally I think, that the scripts shouldn't ever be edited via the DOCUMENTS MANAGER.

I guess it would be important to look at the JavaScript engine running on the server. This will become important when compiling. Example: PortalScripting supports the usage of `(arg) => return arg` (Arrow functions) but does not support the `let` keyword. From my PortalScripting API:

![image](https://user-images.githubusercontent.com/7669818/27585090-158ba846-5b3b-11e7-970b-40673aaefe7b.png)

The user would have to be able to configure the Documents Version in the plugin so that the compiler would be able to work correctly.

**Comment by tineheller** [comment]
Well yes the user will have to be able to configure the DOCUMENTS version anyway sooner or later.

But you are right. Another problem are the ECMAScript versions.
> ![](https://user-images.githubusercontent.com/7669818/27585090-158ba846-5b3b-11e7-970b-40673aaefe7b.png)

The typescript compiler that I use in the extension can output JavaScript files in ES5 or in ES6. But not a mix of both.

**Comment by tineheller** [comment]
TypeScript files are compiled to ES5.
Done with aee91b4ba411718227bea3edfb0dc52db19c00d1.

**Comment by FabianTe** [comment]
Quick question, posting here since there is no place to have a discussion:

Did you have to specify any important settings in the ts compilations options?
I currently try using ts myself and will need to convert it to DOCUMENTS compatible js code. (without the vscode extension)

**Comment by bkircher** [comment]
Hi @FabianTe. You can always open a new issue for questions :wink: Just add the "question" tag to the issue and start the discussion.
