### ISSUE TITLE
Set script parameters in vscode 

### ISSUE THREAD

**Issue by FabianTe** [otris/vscode-janus-debug#95]
Will it be possible to configure / change / add script parameters from the vscode editor?
This would enhance the users workflow drasticly.

**Comment by tineheller** [comment]
We think about it. One idea by now is, to add the parameters as a JSON string in a comment into the script. Then you could change the parameters by changing the JSON string. It's not the nicest idea, so we are still looking for better ideas!

**Comment by FabianTe** [comment]
What about a second file ```my-script.params.json```? Maybe you could configure the plugin to have vscode aid the user with editing this file (vscode does this already with files like ```jsconfig.json``` and so on)

**Comment by tineheller** [comment]
Actually we want to avoid additional files. The advantage of the JSON string in a comment is, that you can see the parameters inside the script, so it's easier to use them.

**Comment by wehrstedt** [comment]
We discussed these problem in our team last year when I implemented the build automation for contract and compliance. We needed the possibility to define somewhere the script parameters and attributes for the build process.
We decided to use one external file for this purpose. We also thought about to include the script parameters inside the script the parameters belongs to. We decide against it because you will add in average 100 to 200 lines in a single script if you want to represent the json structure in a human readable form. Another reason is that you can see what parameters are defined in your whole repository at once and don't have to search in each script if there is something defined. By doing this we found a lot of parameters which were depricated and we removed them. Additionaly it's not practiable to add the json structure in the same script because when you add a parameter to a script you normaly implement something in the same script and want to use the parameter definiton as a reference for your implementation. By doing this you have to scroll a lot between the parameter definition and the implementation.

My main purpose is that I implemented grunt functions for export script parameters and script attributes to a json file. You could use this function to save you a lot of work. Also I implemented a script which attach these parameters to the script again after uploading. Maybe you can use this too,

At least it would be nice to support an external json file so I don' have to make too much changes on my side.

**Comment by tineheller** [comment]
> At least it would be nice to support an external json file so I don' have to make too much changes on my side.

But you know that you can get a json file (`jscript.specs.json`) that contains all parameters by choosing **Get Script Parameters** from context menu in VS Code explorer? What about that file? is it ok?

**Comment by wehrstedt** [comment]
@tineheller As discussed. Didn't saw that it's already possible. But thats exactly the same structure I need for my purpose

**Comment by tineheller** [comment]
I think I will keep that file and provide a command like `Set Parameters`. If this command is executed, the parameters will be set to all scripts.

**Comment by tineheller** [comment]
We decided that script parameters will be written to one file per script. Meaning, if the command **Get Script Parameters** is called, one file for each script will be created in a seperate folder.

So for instance, the script parameters of `myScript.js` will be written to `${workspaceRoot}/.scriptParameters/myScript.specs.json`

That way it will be possible to upload the script parameters on every upload automatically if a parameter file is found. And the parameters can be set in that files.

For next release only **Get Script Parameter** will be supported. The possibility to set parameters with the extension will be available in a later release.

**Comment by FabianTe** [comment]
> one file for each script will be created in a seperate folder.

I'd make that folder configurable

> So for instance, the script parameters of myScript.js will be written to ```${workspaceRoot}/.scriptParameters/myScript.specs.json```

Is it an option to just name the files ```scriptname.json```? Since they are already in a dedicated parameters folder there is no need to have them be like ```scriptname.specs.json```

**Comment by tineheller** [comment]
> Is it an option to just name the files `scriptname.json`? Since they are already in a dedicated parameters folder there is no need to have them be like `scriptname.specs.json`

Well probably you're right. I've changed it. So now the name of the parameter file is just `scriptname.json`.

> I'd make that folder configurable

Ok maybe later, but it won't be configurable for now.

**Comment by wehrstedt** [comment]
It would be nice if it's possible to download the script paramters from a single file only. For now its only possible to download the parameters of all scripts.

Additionally it would be awesome if there is a command to download the script parameters of only those files which are in my opened workspace. The reason is that the server contains scripts which are not part of the opened project and I had to delete those files every time I want to update the script parameters file.

**Comment by tineheller** [comment]
With #124 and #123 it will be possible to download the parameters of only one script or of all scripts in your workspace folder and all subfolders.
